program tests

  ! Driver program for FRUIT unit tests in:
  ! src/day20b_test.f90

  ! Generated by FRUITPy.

  use fruit
  use day20b_test

  implicit none
  integer :: failed_count

  call init_fruit

  call run_test_case(test_name_to_id_to_name_short,"test_name_to_id_to_name_short")
  call run_test_case(test_name_to_id_to_name_long,"test_name_to_id_to_name_long")
  call run_test_case(test_solve_input,"test_solve_input")

  call get_failed_count(failed_count)
  call fruit_summary
  call fruit_finalize
  if (failed_count > 0) stop 1

end program tests